// FLORIDA REAL ESTATE EXAM - COMPREHENSIVE STUDY DATA v2.1
// All 19 Sections

export const HISTORICAL_TIMELINE = [
  { year: 1866, event: "Civil Rights Act of 1866", category: "civil-rights", description: "First federal law guaranteeing equal property rights regardless of race.", impact: "Jones v. Mayer (1968) upheld this - racial discrimination has NO exemptions.", examTip: "Mrs. Murphy exemption NEVER applies to race." },
  { year: 1934, event: "FHA Created - Redlining", category: "fair-housing", description: "Government institutionalized redlining - refusing loans in minority neighborhoods.", impact: "Government-sponsored discrimination prevented wealth-building.", examTip: "Redlining is now ILLEGAL." },
  { year: 1948, event: "Shelley v. Kraemer", category: "fair-housing", description: "Courts cannot enforce racially restrictive covenants.", impact: "Racial deed restrictions unenforceable.", examTip: "Old deeds may contain unenforceable restrictions." },
  { year: 1968, event: "Fair Housing Act", category: "fair-housing", description: "Passed 1 week after MLK assassination. Protected Race, Color, Religion, National Origin.", impact: "Housing discrimination became federal crime.", examTip: "Know when classes added: 1968(4), 1974(Sex), 1988(2 more)." },
  { year: 1968, event: "Jones v. Mayer", category: "fair-housing", description: "Racial discrimination prohibited with NO exemptions.", impact: "Mrs. Murphy does NOT apply to race.", examTip: "Race + any exemption = ALWAYS illegal." },
  { year: 1974, event: "Sex Added", category: "fair-housing", description: "Sex added as 5th protected class.", impact: "Women protected from discrimination.", examTip: "Timeline: 1968(4), 1974(+Sex), 1988(+2)." },
  { year: 1978, event: "Lead Paint Banned", category: "environmental", description: "Lead paint banned in residential housing.", impact: "Pre-1978 homes require disclosure.", examTip: "1978 = magic date for lead." },
  { year: 1988, event: "Fair Housing Amendments", category: "fair-housing", description: "Added Familial Status and Disability.", impact: "Now 7 federal protected classes.", examTip: "55+ can exclude children, not other classes." },
  { year: 1992, event: "Lead Disclosure Act", category: "environmental", description: "Created specific disclosure requirements.", impact: "EPA pamphlet, 10-day inspection required.", examTip: "Disclose KNOWN hazards only." },
  { year: 1997, event: "FL Transaction Broker Default", category: "florida-law", description: "FL changed default to transaction broker.", impact: "Transaction broker presumed.", examTip: "Single Agent = fiduciary. TB = NOT." }
];

export const CASE_STUDIES = [
  // FAIR HOUSING CASES
  { id: 1, title: "The Mrs. Murphy Trap", category: "fair-housing", difficulty: "hard", scenario: "Sarah owns a duplex, lives in one unit. Tells agent: 'I only want white tenants.' Agent remembers Mrs. Murphy exemption for owner-occupied 4 units or less.", question: "Can the agent legally help Sarah find only white tenants?", answer: "ABSOLUTELY NOT. Two fatal problems:\n\n1. JONES v. MAYER (1968): Civil Rights Act of 1866 prohibits ALL racial discrimination with NO exemptions. Mrs. Murphy NEVER applies to race.\n\n2. AGENT INVOLVEMENT: Using an agent eliminates even Fair Housing exemptions.\n\nPenalties: $100K+ civil penalties, license revocation, criminal charges possible.", examRelevance: "Mrs. Murphy + Race = ALWAYS illegal. Agent involvement removes all exemptions.", keyPoints: ["Jones v. Mayer = no racial exemptions", "Agent involvement removes exemptions", "Both face massive penalties"] },
  { id: 2, title: "Steering With a Smile", category: "fair-housing", difficulty: "medium", scenario: "Agent Marcus shows homes to Black family. Says: 'You'd be more comfortable in Eastside - more diversity there. Schools in Riverside aren't rated as highly anyway.'", question: "Has Marcus violated fair housing law? Does his good intent matter?", answer: "YES, illegal STEERING. NO, intent doesn't matter.\n\nSteering = directing buyers based on protected class. Marcus's 'helpful' suggestions are textbook steering.\n\nRed flags: 'more comfortable,' 'more diversity,' 'better fit'\n\nCorrect approach: Provide objective info, let buyers decide.", examRelevance: "Steering illegal even with good intentions. Watch for 'comfortable' and 'fit' language.", keyPoints: ["Intent doesn't matter - impact does", "Agents provide objective info only", "Buyers decide where to look"] },
  { id: 3, title: "The Disability Accommodation", category: "fair-housing", difficulty: "medium", scenario: "Tenant in wheelchair requests assigned parking spot near building entrance. HOA says 'Our rules don't allow assigned parking - everyone uses first-come-first-served.' They offer no alternatives.", question: "Is the HOA in compliance with Fair Housing?", answer: "NO - Fair Housing violation.\n\nLandlords/HOAs must make REASONABLE ACCOMMODATIONS for disabilities. An assigned parking spot is a reasonable accommodation that:\n• Costs the HOA nothing\n• Doesn't fundamentally alter operations\n• Is necessary for equal enjoyment\n\nThe HOA must grant the request or provide equivalent accommodation.", examRelevance: "Reasonable accommodations are REQUIRED for disabilities. 'Our rules don't allow it' is not a valid defense.", keyPoints: ["Must accommodate disabilities", "Rules must bend for reasonable requests", "No extra cost to tenant"] },
  
  // ENVIRONMENTAL CASES
  { id: 4, title: "The Lead Paint Trap", category: "environmental", difficulty: "medium", scenario: "Tom sells his 1965 home. Never tested for lead. Tells buyer confidently: 'No lead paint here - been repainted several times.'", question: "Has Tom fulfilled disclosure obligations?", answer: "NO - potential FRAUD.\n\nTom said 'no lead paint' without ANY basis. Repainting doesn't remove lead.\n\nRequired: Disclose KNOWN hazards, provide EPA pamphlet, offer 10-day inspection.\n\nCorrect statement: 'I have no knowledge of lead hazards. Home never tested.'\n\nPenalties: Up to $16,773 per violation plus civil liability.", examRelevance: "Disclose what you KNOW. Cannot claim 'no lead' without testing.", keyPoints: ["1978 = magic date", "Disclose KNOWN hazards only", "Never claim 'no lead' without test"] },
  { id: 5, title: "The Radon Surprise", category: "environmental", difficulty: "easy", scenario: "Buyer asks seller about radon. Seller says 'I've lived here 20 years with no health problems, so there's obviously no radon issue.' Seller never tested.", question: "Is this adequate radon disclosure?", answer: "NO - Misleading statement.\n\nRadon is odorless and invisible. Health effects take years to develop. Living somewhere without immediate symptoms proves nothing.\n\nFlorida requires radon disclosure statement in contracts. Seller should say: 'I have not tested for radon and have no knowledge of radon levels.'\n\nBuyer should be informed of right to test.", examRelevance: "Radon disclosure required in FL. Cannot make claims without testing.", keyPoints: ["Radon is invisible/odorless", "FL requires disclosure", "Recommend testing"] },
  
  // BROKERAGE/ESCROW CASES
  { id: 6, title: "The Escrow Standoff", category: "brokerage", difficulty: "hard", scenario: "Broker holds $15K escrow. Deal falls apart over inspection issues. Buyer wants money back, seller claims breach. Both demanding release.", question: "What are broker's legal options?", answer: "4 ESCAPE PROCEDURES:\n\n1. MEDIATION - If contract requires\n2. ARBITRATION - If both parties agree\n3. INTERPLEADER - Court action (releases broker)\n4. FREC EDO - FREC decides\n\nMust notify FREC within 15 business days for mediation/arbitration.\n\nBroker must NEVER take sides. Wrong disbursement = personal liability.", examRelevance: "Memorize 4 procedures. 15-day FREC notification. Interpleader releases broker.", keyPoints: ["4 escape procedures", "15 business days to notify FREC", "Never take sides"] },
  { id: 7, title: "The Late Deposit", category: "brokerage", difficulty: "easy", scenario: "Contract accepted Thursday evening. Broker receives earnest money check Friday but is busy with closings. Deposits it the following Wednesday.", question: "Has the broker violated escrow rules?", answer: "YES - Escrow violation.\n\nDeadline: End of 3rd BUSINESS day after acceptance.\n• Thursday acceptance\n• Day 1: Friday\n• Day 2: Monday\n• Day 3: Tuesday\n\nDeposit was due by end of Tuesday. Wednesday is late.\n\nConsequences: License discipline, fines up to $5,000, potential liability.", examRelevance: "3rd BUSINESS day deadline. Weekends don't count. No excuses.", keyPoints: ["3rd business day", "Weekends excluded", "No extensions for being busy"] },
  { id: 8, title: "The Personal Funds Problem", category: "brokerage", difficulty: "medium", scenario: "Broker keeps $7,500 of personal funds in escrow account 'just in case' for bank fees and minimum balance. Another broker keeps $4,000.", question: "Which broker is in violation?", answer: "The $7,500 broker is in VIOLATION.\n\nRule: Broker may keep up to $5,000 personal funds in SALES escrow account for bank fees and minimum balance.\n\n• $7,500 > $5,000 = COMMINGLING violation\n• $4,000 < $5,000 = Acceptable\n\nCommingling = mixing personal and escrow funds = license violation.", examRelevance: "$5,000 maximum personal funds in sales escrow.", keyPoints: ["$5,000 max personal funds", "Prevents commingling", "Sales escrow only"] },
  
  // AGENCY CASES
  { id: 9, title: "The Fiduciary Dilemma", category: "agency", difficulty: "hard", scenario: "Single agent Jane represents buyer Bob. While Bob's on phone, seller whispers: 'We're desperate - would take $50K less.' Bob returns, unaware.", question: "Must Jane tell Bob?", answer: "YES - MUST disclose immediately.\n\nAs SINGLE AGENT, Jane owes FULL fiduciary duties (OLD CAR):\n• Obedience\n• Loyalty - Bob's interest FIRST\n• Disclosure - ALL material info\n• Confidentiality\n• Accountability\n• Reasonable skill\n\nSeller's motivation is MATERIAL info affecting negotiation.\n\nIf Jane were TRANSACTION BROKER: Would NOT disclose (limited confidentiality to both).", examRelevance: "Single agent = full fiduciary, disclose everything. Transaction broker = limited duties.", keyPoints: ["OLD CAR duties for single agent", "Material info must be disclosed", "Agency type changes obligations"] },
  { id: 10, title: "The Default Relationship", category: "agency", difficulty: "easy", scenario: "Buyer walks into open house. Agent starts showing property, discussing terms, never mentions agency. Buyer assumes agent is 'their' agent.", question: "What relationship exists? What should have happened?", answer: "TRANSACTION BROKER by default.\n\nSince 1997, Florida presumes TRANSACTION BROKER unless disclosed otherwise. The agent should have:\n\n1. Provided brokerage relationship disclosure BEFORE showing\n2. Explained transaction broker duties\n3. Offered single agent option if available\n\nBuyer is NOT getting fiduciary representation - just 'limited' duties.", examRelevance: "FL default = Transaction Broker. Must disclose before substantive discussions.", keyPoints: ["Transaction broker is default", "Disclose BEFORE showing", "Not a fiduciary relationship"] },
  { id: 11, title: "The Dual Agency Disaster", category: "agency", difficulty: "hard", scenario: "Agent Lisa represents seller. Unrepresented buyer asks Lisa to write their offer. Lisa agrees and negotiates for both sides without any disclosure.", question: "What violations occurred?", answer: "MULTIPLE serious violations:\n\n1. UNDISCLOSED DUAL AGENCY - Must have written consent from BOTH parties\n2. CONFLICT OF INTEREST - Can't negotiate against your own client\n3. BREACH OF FIDUCIARY DUTY - Seller's interests not protected\n4. FAILURE TO DISCLOSE - No agency disclosure given to buyer\n\nLisa could face license suspension/revocation and civil liability to both parties.", examRelevance: "Dual agency requires written consent from BOTH parties. Undisclosed dual agency = serious violation.", keyPoints: ["Written consent required", "Must disclose to both", "Can't serve two masters secretly"] },
  
  // CONTRACT CASES
  { id: 12, title: "The Commission That Wasn't", category: "contracts", difficulty: "medium", scenario: "Sales associate Mike worked 3 months with buyers. 52 showings. Clearly procuring cause. But no written agreements with FSBO seller or buyers. Seller refuses to pay.", question: "Can Mike or his broker collect?", answer: "NO - Multiple barriers:\n\n1. STATUTE OF FRAUDS: Commission agreements must be WRITTEN\n2. ONLY BROKER can sue: Mike has no standing\n3. PROCURING CAUSE isn't enough without written agreement\n4. SA paid ONLY by employing broker\n\n3 months work = $0. Lesson: GET IT IN WRITING first.", examRelevance: "Written commission agreement required. Only broker can sue. SA paid by broker only.", keyPoints: ["Statute of Frauds = written required", "Only broker sues for commission", "Get agreements BEFORE working"] },
  { id: 13, title: "The Verbal Listing", category: "contracts", difficulty: "easy", scenario: "Seller verbally agrees to list with broker at 6% commission. Broker markets property, finds buyer. At closing, seller refuses to pay: 'We never signed anything.'", question: "Can broker collect the commission?", answer: "NO - Unenforceable agreement.\n\nSTATUTE OF FRAUDS requires listing agreements to be IN WRITING.\n\nOral listing = UNENFORCEABLE (not void, but can't enforce in court)\n\nBroker did real work but has no legal remedy. Expensive lesson about getting signatures BEFORE marketing.", examRelevance: "Statute of Frauds applies to listings and commission agreements.", keyPoints: ["Listings must be written", "Oral = unenforceable", "Get signed BEFORE working"] },
  { id: 14, title: "The Unauthorized Practice", category: "contracts", difficulty: "medium", scenario: "Buyers ask agent Jennifer about 'specific performance' clause meaning and tax implications of purchase. Jennifer explains legal rights and gives tax advice.", question: "Has Jennifer done anything wrong?", answer: "YES - Two violations:\n\n1. UNAUTHORIZED PRACTICE OF LAW: Cannot advise on legal rights, remedies, or court outcomes\n\n2. UNLICENSED TAX ADVICE: Cannot provide specific tax guidance\n\nJennifer CAN explain what words mean generally.\nJennifer CANNOT advise on rights or give legal/tax opinions.\n\nCorrect: 'For legal advice, consult an attorney. For tax questions, see a CPA.'", examRelevance: "Know line between explaining and practicing law. Refer to professionals.", keyPoints: ["Cannot practice law", "Cannot give tax advice", "Refer to attorneys/CPAs"] },
  
  // MORTGAGE/FINANCE CASES
  { id: 15, title: "The Down Payment Dilemma", category: "mortgages", difficulty: "easy", scenario: "First-time buyer has excellent credit but only $10,000 saved. Wants to buy $280,000 home. Agent says 'You need 20% down - that's $56,000. You can't afford this.'", question: "Is the agent's advice correct?", answer: "NO - Agent is WRONG and potentially losing a sale.\n\nOptions for low down payment:\n• FHA: 3.5% down = $9,800 ✓ Buyer qualifies!\n• VA: 0% down (if veteran)\n• Conventional: As low as 3-5% with PMI\n\nThe 20% is only to AVOID PMI, not a requirement.\n\nAgent should refer to lender for pre-qualification, not make lending decisions.", examRelevance: "Know down payment requirements: FHA 3.5%, VA 0%, Conventional varies. Don't discourage buyers.", keyPoints: ["FHA = 3.5%", "VA = 0%", "20% only avoids PMI", "Refer to lender"] },
  { id: 16, title: "The Points Confusion", category: "mortgages", difficulty: "medium", scenario: "Buyer is getting $300,000 loan. Lender offers to reduce rate by 0.25% if buyer pays 2 points. Buyer asks agent: 'What will 2 points cost me?'", question: "What is the cost of 2 points?", answer: "$6,000\n\nCalculation:\n• 1 point = 1% of LOAN amount (not purchase price)\n• 2 points = 2% of $300,000\n• 2% × $300,000 = $6,000\n\nPoints are prepaid interest paid at closing to buy down the interest rate. Whether it's worth it depends on how long buyer keeps the loan.", examRelevance: "1 point = 1% of LOAN amount. Prepaid interest to reduce rate.", keyPoints: ["Point = 1% of loan", "Not purchase price", "Prepaid interest"] },
  
  // APPRAISAL CASES
  { id: 17, title: "The Comparable Adjustment", category: "appraisal", difficulty: "medium", scenario: "Appraiser values home with pool. Comparable sale has no pool. Pools add $15,000 value in this market.", question: "How does appraiser adjust?", answer: "ADD $15,000 TO THE COMPARABLE.\n\nRule: Always adjust the COMPARABLE, not the subject.\n\n• Comparable LACKS feature subject has → ADD to comparable\n• Comparable HAS feature subject lacks → SUBTRACT from comparable\n\nLogic: We're asking 'What would the comparable have sold for if it had the same features as subject?'\n\nThe comparable without pool would have sold for MORE if it had a pool.", examRelevance: "Adjust the COMPARABLE. Lacks = Add, Has extra = Subtract.", keyPoints: ["Adjust comparable only", "Lacks feature = ADD", "Has extra = SUBTRACT"] },
  { id: 18, title: "The External Obsolescence", category: "appraisal", difficulty: "hard", scenario: "Beautiful home, perfect condition. But new highway built 100 feet from backyard. Noise is constant. Value dropped $50,000.", question: "What type of depreciation is this? Can owner fix it?", answer: "EXTERNAL (Economic) OBSOLESCENCE - INCURABLE.\n\nThree types of depreciation:\n• Physical: Wear and tear (often curable)\n• Functional: Outdated design (sometimes curable)\n• External: Outside factors (ALWAYS incurable)\n\nThe highway is EXTERNAL - owner can't move or silence it. This depreciation is permanent and incurable.\n\nExamples: Airport noise, factory nearby, neighborhood decline.", examRelevance: "External obsolescence is ALWAYS incurable. Caused by factors outside the property.", keyPoints: ["External = outside factors", "Always incurable", "Can't fix what you don't control"] },
  
  // PROPERTY RIGHTS CASES
  { id: 19, title: "The Joint Tenancy Break", category: "property-rights", difficulty: "hard", scenario: "A, B, and C own property as joint tenants. A secretly sells his interest to D without telling B and C.", question: "What happens to the ownership?", answer: "Joint tenancy is PARTIALLY SEVERED.\n\nOriginal: A, B, C as joint tenants (survivorship)\n\nAfter A sells to D:\n• B and C remain joint tenants WITH EACH OTHER\n• D becomes tenant in common with B and C\n• D has NO survivorship rights\n\nThe PITT unities (Possession, Interest, Time, Title) were broken when A transferred to D. D didn't acquire at same time or by same deed.", examRelevance: "Selling joint tenancy interest severs it. New owner becomes TIC.", keyPoints: ["Sale severs joint tenancy", "New owner is TIC", "Remaining JTs keep survivorship"] },
  { id: 20, title: "The Entireties Protection", category: "property-rights", difficulty: "medium", scenario: "Married couple owns home as tenants by the entireties. Husband gets sued personally for business debt. Creditor wants to force sale of home.", question: "Can the creditor force the sale?", answer: "NO - Tenancy by entireties provides CREDITOR PROTECTION.\n\nKey features of entireties:\n• MARRIED couples only\n• Right of survivorship\n• Neither can sell without other's consent\n• CREDITOR PROTECTION from individual debts\n\nThe creditor sued HUSBAND only. Can't touch property owned as entireties.\n\nIf creditor had sued BOTH spouses, different result.", examRelevance: "Entireties protects from INDIVIDUAL creditors. Married only.", keyPoints: ["Married couples only", "Creditor protection", "Can't force sale for one spouse's debt"] },
  
  // TAX CASES
  { id: 21, title: "The Homestead Mistake", category: "taxes", difficulty: "medium", scenario: "Owner claims homestead exemption on Florida home. Then buys second home in Georgia and claims homestead there too, while renting out Florida home.", question: "What are the consequences?", answer: "SERIOUS consequences:\n\n1. FRAUD - Can only have ONE homestead\n2. Back taxes owed with PENALTIES and INTEREST\n3. Potential criminal charges\n4. Loss of exemption going forward\n\nHomestead exemption requires:\n• Primary residence\n• Florida resident\n• Only ONE homestead allowed\n\nRenting out the property = no longer primary residence = no exemption.", examRelevance: "Only ONE homestead. Must be primary residence. Fraud has serious consequences.", keyPoints: ["One homestead only", "Must be primary residence", "Fraud = back taxes + penalties"] },
  { id: 22, title: "The Early Payment Discount", category: "taxes", difficulty: "easy", scenario: "Property tax bill is $4,000. Owner wants maximum discount. It's currently October 15th.", question: "When should owner pay and how much will they save?", answer: "Pay in NOVEMBER for 4% discount.\n\nFlorida early payment discounts:\n• November: 4% off = $160 saved\n• December: 3% off = $120 saved\n• January: 2% off = $80 saved\n• February: 1% off = $40 saved\n• March: Full amount due\n\nNovember payment: $4,000 - $160 = $3,840\n\nTaxes are DUE November 1, DELINQUENT April 1.", examRelevance: "November = 4% discount. Know the discount schedule.", keyPoints: ["Nov 4%, Dec 3%, Jan 2%, Feb 1%", "Due Nov 1", "Delinquent Apr 1"] },
  
  // ZONING/LAND USE CASES
  { id: 23, title: "The Variance Request", category: "zoning", difficulty: "medium", scenario: "Owner's lot is oddly shaped due to road curve. Cannot meet required 25-foot setback and still build reasonable home. Requests variance.", question: "Will the variance likely be granted? Why?", answer: "LIKELY YES - This shows HARDSHIP.\n\nVariance requirements:\n• Hardship NOT self-created\n• Due to unique property characteristics\n• Won't harm neighborhood character\n• Minimum variance necessary\n\nThe odd lot shape is NOT owner's fault - it's a characteristic of the land. This is exactly what variances are for.\n\nContrast: Variance denied if owner created the problem (like subdividing their own lot too small).", examRelevance: "Variance = hardship exception. Must not be self-created.", keyPoints: ["Hardship required", "Not self-created", "Unique property characteristic"] },
  { id: 24, title: "The Nonconforming Use", category: "zoning", difficulty: "medium", scenario: "Gas station has operated since 1960. Area rezoned residential in 1990. Station continues operating legally. Fire destroys building in 2024.", question: "Can owner rebuild the gas station?", answer: "PROBABLY NOT - Nonconforming use typically can't be rebuilt.\n\nNonconforming use rules:\n• Can CONTINUE existing use (grandfathered)\n• Usually can't EXPAND\n• If DESTROYED (typically 50%+ damage), can't rebuild\n• Use eventually phases out\n\nThe gas station was legal nonconforming. But destruction usually terminates the right to continue. Owner likely must conform to current residential zoning.\n\nCheck local ordinances - rules vary.", examRelevance: "Nonconforming use = grandfathered. Destruction usually ends the right.", keyPoints: ["Can continue, can't expand", "Destruction ends right", "Eventually phases out"] }
];

export const EXAM_SECTIONS = [
  { id: 1, title: "The Real Estate Business", percentage: 1, color: "#3B82F6", topics: ["Characteristics", "Organizations"], content: "**UNIQUE CHARACTERISTICS:**\n• HETEROGENEITY - No two parcels alike\n• IMMOBILITY - Cannot be moved\n• DURABILITY - Land permanent\n\n**KEY TERMS:**\n• REALTOR® = NAR trademark, members only\n• Real Property = Land + improvements + rights\n• Personal Property = Movable items (chattels)", flashcards: [{ front: "3 unique RE characteristics?", back: "HETEROGENEITY - No two alike\nIMMOBILITY - Can't move\nDURABILITY - Permanent\n\nMemory: HID" }, { front: "REALTOR® means?", back: "NAR trademark. Only dues-paying NAR members can use it. Not all agents are REALTORS®." }, { front: "Real vs personal property?", back: "REAL: Land + improvements (immovable)\nPERSONAL: Movable items (chattels)\n\nMARIA test for fixtures" }], practiceQuestions: [{ question: "No two parcels alike:", options: ["Durability", "Immobility", "Heterogeneity", "Scarcity"], correct: 2, explanation: "HETEROGENEITY = unique. Each parcel different by location." }, { question: "REALTOR® refers to:", options: ["Any agent", "NAR members only", "Brokers only", "Anyone"], correct: 1, explanation: "REALTOR® is NAR trademark. Only members can use it." }] },
  { id: 2, title: "License Law & Qualifications", percentage: 6, color: "#10B981", topics: ["Chapter 475", "Requirements", "Education"], content: "**SA REQUIREMENTS:**\n• Age 18+, HS diploma\n• 63-hr pre-license (FREC I)\n• 75% exam (75/100)\n• 45-hr post-license before renewal\n• 14-hr CE every 2 years\n\n**POST-LICENSE:** Failure = NULL AND VOID\n\n**BROKER:** 24 months active SA in preceding 5 years + 72-hr course", flashcards: [{ front: "Education hours?", back: "PRE-LICENSE: 63 hours\nPOST-LICENSE: 45 hours\nCONTINUING ED: 14 hours/2yrs\n\nMemory: 63→45→14" }, { front: "Passing score?", back: "75% = 75 out of 100\n3.5 hours to complete" }, { front: "Broker experience?", back: "24 months ACTIVE SA in preceding 5 years\nPlus 72-hr course + exam" }, { front: "Post-license not completed?", back: "License NULL AND VOID\nMust start completely over" }], practiceQuestions: [{ question: "Minimum age:", options: ["16", "18", "21", "25"], correct: 1, explanation: "18 = age of majority to enter contracts." }, { question: "Pre-license hours:", options: ["45", "63", "72", "90"], correct: 1, explanation: "63 hours (FREC Course I)" }, { question: "Post-license deadline:", options: ["First closing", "First renewal", "6 months", "5 years"], correct: 1, explanation: "Before first renewal. Failure = NULL AND VOID." }] },
  { id: 3, title: "FREC Rules", percentage: 2, color: "#8B5CF6", topics: ["Composition", "Powers", "DBPR"], content: "**FREC - 7 MEMBERS:**\n• 4 brokers (5+ yrs)\n• 1 broker/SA (2+ yrs)\n• 2 consumers (NEVER licensed)\n\n**APPOINTMENT:** Governor appoints, Senate confirms\n**TERMS:** 4 years, max 2 consecutive\n\n**POWERS:**\n• Fines up to $5,000/violation\n• Suspend, revoke licenses\n• Probation, education\n\n**DBPR** = parent agency", flashcards: [{ front: "FREC composition?", back: "7 MEMBERS:\n• 4 brokers (5+ yrs)\n• 1 broker/SA (2+ yrs)\n• 2 consumers (never licensed)\n\nGovernor appoints, Senate confirms" }, { front: "Max fine?", back: "$5,000 PER VIOLATION\n\n3 violations = up to $15,000" }, { front: "DBPR vs FREC?", back: "DBPR = Parent agency\nFREC = RE division\n\nDBPR investigates\nFREC holds hearings" }], practiceQuestions: [{ question: "FREC members:", options: ["5", "7", "9", "11"], correct: 1, explanation: "7 members: 4 brokers + 1 broker/SA + 2 consumers" }, { question: "Max fine/violation:", options: ["$1K", "$2.5K", "$5K", "$10K"], correct: 2, explanation: "$5,000 per violation" }, { question: "Consumer members:", options: ["Inactive license", "RE experience", "Never licensed", "21+"], correct: 2, explanation: "Never been licensed - true consumer perspective" }] },
  { id: 4, title: "Brokerage Relationships", percentage: 7, color: "#F59E0B", topics: ["Transaction Broker", "Single Agent", "Disclosure"], content: "**FL DEFAULT = TRANSACTION BROKER**\nLimited, NOT fiduciary\n\n**SINGLE AGENT = FIDUCIARY**\nOLD CAR:\n• Obedience\n• Loyalty\n• Disclosure\n• Confidentiality\n• Accountability\n• Reasonable skill\n\n**NO BROKERAGE** = Customer, honesty only", flashcards: [{ front: "FL default relationship?", back: "TRANSACTION BROKER\nLimited, NOT fiduciary\nSince 1997" }, { front: "OLD CAR duties?", back: "Single Agent fiduciary:\n• Obedience\n• Loyalty\n• Disclosure\n• Confidentiality\n• Accountability\n• Reasonable skill" }, { front: "Client vs Customer?", back: "CLIENT = Represented\nCUSTOMER = Not represented\n\nCustomers owed only honesty" }, { front: "Single agent vs TB?", back: "SINGLE AGENT: Full fiduciary, OLD CAR\nTRANSACTION BROKER: Limited, NOT fiduciary" }], practiceQuestions: [{ question: "FL default:", options: ["Single agent", "Transaction broker", "Dual", "No brokerage"], correct: 1, explanation: "Transaction broker presumed since 1997" }, { question: "Fiduciary duties:", options: ["TB", "Single agent", "No brokerage", "All"], correct: 1, explanation: "Single agent ONLY = fiduciary (OLD CAR)" }, { question: "OLD CAR applies to:", options: ["TB", "Single agent", "No brokerage", "Customer"], correct: 1, explanation: "Single agent only" }] },
  { id: 5, title: "Brokerage Activities", percentage: 12, color: "#EF4444", topics: ["Escrow", "Commission", "Antitrust"], content: "**ESCROW:**\n• Deposit by 3rd BUSINESS day\n• $5K personal allowed\n• Commingling = violation\n• Conversion = CRIMINAL\n\n**4 DISPUTE PROCEDURES:**\n1. Mediation\n2. Arbitration\n3. Interpleader\n4. FREC EDO\n(15 business days FREC notice)\n\n**COMMISSION:**\n• Always NEGOTIABLE\n• Only BROKER sues\n• SA paid by broker only\n• Must be WRITTEN\n\n**ANTITRUST:**\n• Price fixing\n• Boycotting\n• Market allocation\n• Tie-in", flashcards: [{ front: "Escrow deadline?", back: "End of 3rd BUSINESS day\n\nExcludes weekends/holidays" }, { front: "4 escrow procedures?", back: "1. Mediation\n2. Arbitration\n3. Interpleader (releases broker)\n4. FREC EDO\n\n15 business days to notify FREC" }, { front: "Commingling vs Conversion?", back: "COMMINGLING: Mixing funds = violation\nCONVERSION: Using funds = CRIMINAL\n\n$5K personal allowed in escrow" }, { front: "Who sues for commission?", back: "BROKER ONLY\n\nSA paid by broker only\nMust be in writing" }, { front: "4 antitrust violations?", back: "1. Price fixing - agreeing on rates\n2. Boycotting - refusing competitors\n3. Market allocation - dividing territory\n4. Tie-in - requiring extras" }], practiceQuestions: [{ question: "Escrow deadline:", options: ["1st", "2nd", "3rd", "5th"], correct: 2, explanation: "3rd BUSINESS day" }, { question: "Agreeing on rates:", options: ["Allocation", "Price fixing", "Boycott", "Tie-in"], correct: 1, explanation: "Price fixing = agreeing on commission rates" }, { question: "Who sues for commission:", options: ["SA", "Broker only", "Either", "Anyone"], correct: 1, explanation: "BROKER ONLY" }] },
  { id: 6, title: "Violations & Penalties", percentage: 3, color: "#DC2626", topics: ["Recovery Fund", "Penalties"], content: "**FREC PENALTIES:**\n• Fines up to $5,000/violation\n• Suspension, revocation\n• Probation, education\n\n**RECOVERY FUND:**\n• $50,000 per transaction\n• $150,000 per licensee (lifetime)\n• Must get judgment first\n• Last resort\n• Payment = AUTO SUSPENSION\n• Repay with interest to reinstate", flashcards: [{ front: "RF max/transaction?", back: "$50,000 per transaction\n$150,000 per licensee lifetime\n\nLast resort - judgment first" }, { front: "What happens when RF pays?", back: "License AUTO SUSPENDED\n\nMust repay FULL + INTEREST" }], practiceQuestions: [{ question: "RF max/transaction:", options: ["$25K", "$50K", "$100K", "$150K"], correct: 1, explanation: "$50,000/transaction, $150,000/licensee" }, { question: "When RF pays:", options: ["Revoked", "Auto suspended", "Probation", "Nothing"], correct: 1, explanation: "Auto suspended until repaid with interest" }] },
  { id: 7, title: "Federal & State Laws", percentage: 3, color: "#7C3AED", topics: ["Fair Housing", "Protected Classes"], content: "**7 PROTECTED CLASSES:**\nRace, Color, Religion, National Origin, Sex, Familial Status, Disability\n\n**PROHIBITED:**\n• Blockbusting - panic selling\n• Steering - directing by class\n• Redlining - denying by neighborhood\n\n**JONES v. MAYER:**\nRace = NO exemptions\nMrs. Murphy NEVER applies to race\n\n**FL SECURITY DEPOSIT:**\n• 15 days (no claim)\n• 30 days (with claim)", flashcards: [{ front: "7 protected classes?", back: "Race, Color, Religion, National Origin, Sex, Familial Status, Disability\n\nRC Cola R N'S FD" }, { front: "Jones v. Mayer?", back: "Race = NO exemptions\n\nMrs. Murphy NEVER applies to race" }, { front: "Steering?", back: "Directing buyers based on protected class\n\nIllegal even with good intentions" }, { front: "Blockbusting?", back: "Inducing panic sales by suggesting protected class moving in hurts values" }, { front: "Security deposit deadlines?", back: "NO CLAIM: 15 days\nWITH CLAIM: 30 days (certified mail)" }], practiceQuestions: [{ question: "Jones v. Mayer:", options: ["FH constitutional", "Race no exemptions", "Steering illegal", "Blockbusting illegal"], correct: 1, explanation: "Race has NO exemptions" }, { question: "Mrs. Murphy applies to:", options: ["All", "All except race", "Race only", "Nothing"], correct: 1, explanation: "All EXCEPT race" }, { question: "Security deposit (no claim):", options: ["7 days", "15 days", "30 days", "60 days"], correct: 1, explanation: "15 days" }] },
  { id: 8, title: "Property Rights", percentage: 8, color: "#059669", topics: ["Estates", "Co-ownership"], content: "**FREEHOLD (Ownership):**\n• Fee Simple Absolute - highest\n• Fee Simple Defeasible - conditional\n• Life Estate - someone's lifetime\n\n**LEASEHOLD (Rental):**\n• Estate for Years - specific term\n• Periodic - auto renews\n• At Will - either terminates\n• At Sufferance - holdover\n\n**CO-OWNERSHIP:**\n• TIC - no survivorship\n• Joint Tenancy - PITT unities, survivorship\n• Entireties - MARRIED only\n\n**RESCISSION:** Condo 15 days, Timeshare 10 days", flashcards: [{ front: "Highest ownership?", back: "FEE SIMPLE ABSOLUTE\n\nUnlimited, transferable, no conditions" }, { front: "PITT unities?", back: "For Joint Tenancy:\n• Possession\n• Interest\n• Time\n• Title\n\nBroken = TIC" }, { front: "Married-only co-ownership?", back: "TENANCY BY ENTIRETIES\n\nSurvivorship, creditor protection\nDivorce = TIC" }, { front: "MARIA test?", back: "Fixture vs personal:\n• Method\n• Adaptability\n• Relationship\n• Intention\n• Agreement" }, { front: "Rescission periods?", back: "CONDO: 15 days\nTIMESHARE: 10 days" }], practiceQuestions: [{ question: "Married-only:", options: ["Joint", "TIC", "Entireties", "Community"], correct: 2, explanation: "Tenancy by entireties" }, { question: "PITT for:", options: ["TIC", "Joint tenancy", "Entireties", "Fee simple"], correct: 1, explanation: "Joint tenancy requires PITT" }, { question: "Condo rescission:", options: ["7", "10", "15", "30"], correct: 2, explanation: "15 days condo, 10 days timeshare" }] },
  { id: 9, title: "Titles & Deeds", percentage: 7, color: "#0EA5E9", topics: ["Deeds", "Liens", "Recording"], content: "**DEEDS (Most→Least protection):**\n• General Warranty - MOST, all defects\n• Special Warranty - grantor's time only\n• Quitclaim - NO warranties\n\n**NOTICE TYPES:**\n• Actual - direct knowledge\n• Constructive - recording\n• Inquiry - red flags\n\n**LIENS:**\n• Property taxes = PRIORITY\n\n**Escheat** = state takes (no heirs)\n**Eminent Domain** = govt takes WITH compensation", flashcards: [{ front: "Most protection deed?", back: "GENERAL WARRANTY\n\nWarrants against ALL defects ever" }, { front: "No warranties deed?", back: "QUITCLAIM\n\nTransfers whatever exists\nUsed for clearing title, family" }, { front: "Constructive notice?", back: "RECORDING creates it\n\nEveryone presumed to know what's recorded" }, { front: "Escheat?", back: "State takes property when owner dies without will or heirs" }, { front: "Priority liens?", back: "PROPERTY TAXES always priority" }], practiceQuestions: [{ question: "Most protection:", options: ["Quitclaim", "Special warranty", "General warranty", "Bargain"], correct: 2, explanation: "General warranty - all defects" }, { question: "Recording creates:", options: ["Actual", "Constructive", "Inquiry", "None"], correct: 1, explanation: "Constructive notice" }, { question: "Priority liens:", options: ["First mortgage", "Judgment", "Property taxes", "Mechanic's"], correct: 2, explanation: "Property taxes always priority" }] },
  { id: 10, title: "Legal Descriptions", percentage: 5, color: "#6366F1", topics: ["Government Survey", "Metes & Bounds"], content: "**THREE METHODS:**\n• Metes & Bounds - oldest, POB\n• Lot & Block - recorded plat\n• Government Survey - sections\n\n**GOVERNMENT SURVEY:**\n• Township = 36 sq miles\n• Section = 640 ACRES\n\n**CALCULATE ACRES:**\nMultiply denominators, divide 640\n\nNE 1/4 of SW 1/4:\n4 × 4 = 16\n640 ÷ 16 = 40 acres", flashcards: [{ front: "Acres in section?", back: "640 ACRES\n\n1 section = 1 sq mile\nTownship = 36 sections" }, { front: "Calculate acreage?", back: "Multiply denominators, divide 640\n\nNE1/4 of SW1/4:\n4×4=16, 640÷16 = 40 acres" }, { front: "Oldest method?", back: "METES AND BOUNDS\n\nLandmarks, distances, directions\nStarts/returns to POB" }], practiceQuestions: [{ question: "NW1/4 of SE1/4:", options: ["20", "40", "80", "160"], correct: 1, explanation: "4×4=16, 640÷16=40 acres" }, { question: "Section contains:", options: ["320", "640", "36", "160"], correct: 1, explanation: "640 acres" }] },
  { id: 11, title: "Contracts", percentage: 12, color: "#EC4899", topics: ["Elements", "Listings", "Disclosures"], content: "**5 ELEMENTS:**\n1. Competent parties (18+)\n2. Offer & acceptance\n3. Consideration\n4. Legal purpose\n5. In writing (Statute of Frauds)\n\n**CONTRACT STATUS:**\n• Valid - enforceable\n• Void - never existed\n• Voidable - can be voided\n• Unenforceable - valid but can't enforce\n\n**LISTINGS:**\n• Exclusive Right to Sell - paid regardless\n• Exclusive Agency - unless owner sells\n• Open - procuring cause wins\n\n**LEAD DISCLOSURE:** Pre-1978 homes", flashcards: [{ front: "5 contract elements?", back: "1. Competent parties (18+)\n2. Offer & acceptance\n3. Consideration\n4. Legal purpose\n5. In writing" }, { front: "Statute of Frauds?", back: "RE contracts must be WRITTEN\n\nOral RE = unenforceable (not void)" }, { front: "Exclusive Right to Sell vs Agency?", back: "RIGHT TO SELL: Paid regardless who sells\nAGENCY: Unless owner sells directly" }, { front: "Lead disclosure?", back: "Homes before 1978\n\n• Disclose KNOWN hazards\n• EPA pamphlet\n• 10-day inspection" }], practiceQuestions: [{ question: "Statute of Frauds:", options: ["Notarized", "Written", "Witnessed", "Recorded"], correct: 1, explanation: "Must be in WRITING" }, { question: "Lead disclosure pre-:", options: ["1968", "1978", "1988", "1998"], correct: 1, explanation: "1978 - when banned" }, { question: "Paid regardless who sells:", options: ["Open", "Exclusive agency", "Exclusive right to sell", "Net"], correct: 2, explanation: "Exclusive right to sell" }] },
  { id: 12, title: "Mortgages", percentage: 9, color: "#14B8A6", topics: ["Lien Theory", "Documents", "Loan Types"], content: "**FL = LIEN THEORY**\n• Borrower keeps title\n• Lender gets lien\n• Judicial foreclosure\n\n**DOCUMENTS:**\n• Note = debt (promise)\n• Mortgage = lien (security)\n\n**CLAUSES:**\n• Acceleration - due on default\n• Alienation - due if sold\n• Defeasance - releases lien\n\n**LOANS:**\n• FHA: 3.5% down, MIP\n• VA: 0% down, no PMI\n• Conventional: ~20%\n\n**1 Point = 1% of loan**", flashcards: [{ front: "FL theory?", back: "LIEN THEORY\n\nBorrower keeps title\nLender gets lien" }, { front: "Note vs Mortgage?", back: "NOTE = promise to repay (debt)\nMORTGAGE = lien (security)" }, { front: "FHA vs VA down?", back: "FHA: 3.5% min (MIP required)\nVA: 0% (no PMI, funding fee)" }, { front: "1 point?", back: "1% of LOAN amount\n\n$200K loan, 2 pts = $4,000" }], practiceQuestions: [{ question: "Lien theory - title holder:", options: ["Lender", "Borrower", "Title co", "State"], correct: 1, explanation: "Borrower keeps title" }, { question: "FHA down:", options: ["0%", "3%", "3.5%", "5%"], correct: 2, explanation: "3.5%" }, { question: "One point:", options: ["0.5% loan", "1% loan", "1% price", "0.125% rate"], correct: 1, explanation: "1% of loan amount" }] },
  { id: 13, title: "Mortgage Sources", percentage: 4, color: "#F97316", topics: ["Primary/Secondary Markets"], content: "**PRIMARY MARKET:**\nWhere loans originate (banks)\n\n**SECONDARY MARKET:**\nWhere loans bought/sold\n\n• Fannie Mae - GSE\n• Freddie Mac - GSE\n• Ginnie Mae - ONLY govt agency (HUD)\n\n**SPECIAL MORTGAGES:**\n• Purchase Money - seller financing\n• Reverse (HECM) - 62+, no payments\n• Package - includes personal property\n• Blanket - multiple properties", flashcards: [{ front: "Primary vs Secondary?", back: "PRIMARY: Loans originate\nSECONDARY: Loans bought/sold" }, { front: "Only govt agency?", back: "GINNIE MAE (GNMA)\n\nFannie/Freddie = GSEs (privately owned)" }, { front: "Reverse mortgage age?", back: "62+ for HECM\n\nNo payments until death/sale/move" }], practiceQuestions: [{ question: "Actual govt agency:", options: ["Fannie", "Freddie", "Ginnie", "All"], correct: 2, explanation: "Ginnie Mae only (HUD)" }, { question: "Reverse mortgage age:", options: ["55", "59.5", "62", "65"], correct: 2, explanation: "62" }] },
  { id: 14, title: "Computations & Closing", percentage: 6, color: "#84CC16", topics: ["Math", "Prorations"], content: "**FORMULAS:**\n• Commission = Price × Rate\n• Value = NOI ÷ Cap Rate\n• LTV = Loan ÷ Value\n\n**PRORATIONS:**\n• 360-day year\n• Seller pays THROUGH closing\n\n**TRANSFER TAXES:**\n• Deed: $0.70/$100\n• Mortgage: $0.35/$100\n• Intangible: 2 mills", flashcards: [{ front: "Commission formula?", back: "Commission = Price × Rate\n\n$300K × 6% = $18,000" }, { front: "Value from income?", back: "Value = NOI ÷ Cap Rate\n\n$50K ÷ 8% = $625,000" }, { front: "Who pays through closing?", back: "SELLER pays through closing day" }], practiceQuestions: [{ question: "$250K, 6% commission:", options: ["$12.5K", "$15K", "$17.5K", "$20K"], correct: 1, explanation: "$250K × 0.06 = $15,000" }, { question: "NOI $60K, cap 10%:", options: ["$500K", "$550K", "$600K", "$650K"], correct: 2, explanation: "$60K ÷ 0.10 = $600,000" }] },
  { id: 15, title: "Markets & Analysis", percentage: 1, color: "#A855F7", topics: ["Supply/Demand"], content: "**MARKET CHARACTERISTICS:**\n• Local, slow to respond\n• High transaction costs\n• Imperfect information\n\n**SUPPLY & DEMAND:**\n• Demand ↑, Supply same → Prices RISE\n• Supply ↑, Demand same → Prices FALL", flashcards: [{ front: "Demand up, supply same?", back: "PRICES RISE\n\nMore buyers for same inventory" }], practiceQuestions: [{ question: "Demand up, supply constant:", options: ["Prices fall", "Prices rise", "Stable", "Volatile"], correct: 1, explanation: "Prices rise" }] },
  { id: 16, title: "Appraisal", percentage: 8, color: "#0891B2", topics: ["Three Approaches", "Depreciation"], content: "**THREE APPROACHES:**\n• Sales Comparison - residential\n• Cost - unique/new\n• Income - investment\n\n**SALES COMPARISON:**\n• Adjust COMPARABLE, not subject\n• Lacks feature → ADD\n• Has extra → SUBTRACT\n\n**INCOME:**\nValue = NOI ÷ Cap Rate\n\n**DEPRECIATION:**\n• Physical - wear\n• Functional - outdated\n• External - ALWAYS incurable", flashcards: [{ front: "Best for residential?", back: "SALES COMPARISON\n\nCompare to similar recent sales" }, { front: "Comparable lacks feature?", back: "ADD to comparable\n\nAlways adjust comparable, not subject" }, { front: "Always incurable depreciation?", back: "EXTERNAL (Economic)\n\nOutside factors owner can't fix" }], practiceQuestions: [{ question: "NOI $50K, cap 10%:", options: ["$400K", "$450K", "$500K", "$550K"], correct: 2, explanation: "$50K ÷ 0.10 = $500,000" }, { question: "Comparable lacks pool:", options: ["Subtract comp", "Add comp", "Subtract subject", "Add subject"], correct: 1, explanation: "Add to comparable" }] },
  { id: 17, title: "Investments", percentage: 2, color: "#D946EF", topics: ["Leverage", "Benefits"], content: "**BENEFITS:**\n• Cash flow, appreciation\n• Tax benefits, leverage\n• Equity buildup\n\n**LEVERAGE:**\nUsing borrowed money\n\n• Positive - return > cost\n• Negative - cost > return", flashcards: [{ front: "Leverage?", back: "Using borrowed money to increase returns\n\nPositive = return > borrowing cost" }], practiceQuestions: [{ question: "Using borrowed money:", options: ["Arbitrage", "Leverage", "Speculation", "Hedging"], correct: 1, explanation: "Leverage" }] },
  { id: 18, title: "Taxes", percentage: 3, color: "#CA8A04", topics: ["Property Tax", "Homestead"], content: "**PROPERTY TAX:**\n• Ad valorem = by value\n• Mill = $1/$1,000\n• Tax = Value × Mills ÷ 1,000\n\n**FL CALENDAR:**\n• Lien: January 1\n• Due: November 1\n• Delinquent: April 1\n\n**DISCOUNTS:**\nNov 4%, Dec 3%, Jan 2%, Feb 1%\n\n**HOMESTEAD:** First $25K exempt", flashcards: [{ front: "Mill?", back: "$1 per $1,000\n\nTax = Value × Mills ÷ 1,000" }, { front: "Delinquent date?", back: "APRIL 1\n\nLien Jan 1, Due Nov 1" }, { front: "Nov discount?", back: "4%\n\nNov 4%, Dec 3%, Jan 2%, Feb 1%" }], practiceQuestions: [{ question: "$150K, 20 mills:", options: ["$2.5K", "$3K", "$3.5K", "$4K"], correct: 1, explanation: "$150K × 20 ÷ 1000 = $3,000" }, { question: "Delinquent:", options: ["Jan 1", "Apr 1", "Nov 1", "Dec 31"], correct: 1, explanation: "April 1" }] },
  { id: 19, title: "Planning & Zoning", percentage: 1, color: "#71717A", topics: ["Govt Powers", "Zoning"], content: "**GOVT POWERS:**\n• Police Power - no compensation (zoning)\n• Eminent Domain - WITH compensation\n• Taxation\n• Escheat - no heirs\n\n**ZONING:**\n• Variance - hardship deviation\n• Nonconforming - grandfathered\n• Spot Zoning - usually illegal\n\n**When conflict: MORE RESTRICTIVE applies**", flashcards: [{ front: "Police vs Eminent Domain?", back: "POLICE: Regulate, NO compensation\nEMINENT: Take, WITH compensation" }, { front: "Variance?", back: "Permission to deviate due to HARDSHIP" }, { front: "Nonconforming use?", back: "Legal use that no longer complies\n\nGranthered, usually can't expand" }], practiceQuestions: [{ question: "Hardship deviation:", options: ["Conditional", "Variance", "Spot zoning", "Nonconforming"], correct: 1, explanation: "Variance" }, { question: "Taking WITH compensation:", options: ["Police power", "Eminent domain", "Escheat", "Taxation"], correct: 1, explanation: "Eminent domain" }] }
];

export const EXAM_STATS = {
  totalSections: 19,
  totalFlashcards: EXAM_SECTIONS.reduce((sum, s) => sum + s.flashcards.length, 0),
  totalQuestions: EXAM_SECTIONS.reduce((sum, s) => sum + s.practiceQuestions.length, 0),
  passingScore: 75,
  totalExamQuestions: 100,
  examDuration: "3.5 hours",
  highWeightSections: EXAM_SECTIONS.filter(s => s.percentage >= 6).map(s => ({ title: s.title, percentage: s.percentage }))
};
